### ISSUE TITLE
Stuck on Google login screen

### ISSUE THREAD

**Issue by chaoscreater** [mantreshkhurana/Google-Bard-electron#5]
I'm using the Windows version and after entering my email, it just gets stuck at this screen:

![image](https://github.com/mantreshkhurana/Google-Bard-electron/assets/18227319/da63d43e-78ce-404e-a570-c2db4d16f09b)

Tried it again a few times, same issue. But if I try a different login, it'll ask me for my password. Not sure why it's not showing anything for my primary email login.

**Comment by mantreshkhurana** [comment]
I'll take a look into it and get back to you asap.

**Comment by chaoscreater** [comment]
I think I know the reason. On my primary email, I've got a passkey configured and so rather than showing the password prompt screen, I get this:

![image](https://github.com/mantreshkhurana/Google-Bard-electron/assets/18227319/95742487-477d-45fc-98bf-505e4d74bf37)

If I choose "Try another way", then I can enter my Google account password. Otherwise, I can just use the PIN (Windows Hello) configured on my machine to auth into my Google account.

To configure passkey, go here:
https://myaccount.google.com/security

and then choose passkey.
